### PR TITLE
Update piggieback dependency from cemerick/piggieback to cider

### PR DESCRIPTION
**Pull request by gnuman**
Problem Statement:-
Could not start lein repl was getting exception 
ERROR: Unhandled REPL handler exception processing message {:id 2c6a0ee4-fe78-42a2-9123-4554022998a6, :op clone}
 Fix:-
Update piggieback deps according to https://github.com/nrepl/piggieback

### CODE REVIEW

**Comment by drapanjanas** [comment]
This is merged with other PR. I am preparing a release. Thank you!

**Comment by dotemacs** [comment]
Considering that this PR already made it into `master` via https://github.com/drapanjanas/re-natal/pull/217, @drapanjanas would you be open to cutting a new release, considering that the version of: `lein-figwheel` is old, but more importantly, the versions of:

* figwheel-sidecar
* cider/piggieback

are so old, that they don't currently work with the current stable CIDER version?

The workaround is to:

    npm install -g https://github.com/drapanjanas/re-natal.git

in order to use the `master` branch with fixes. 
Or to use the latest stable release and apply the fixes manually.

Thank you

**Comment by drapanjanas** [comment]
@dotemacs done, please try v0.11.0

**Comment by dotemacs** [comment]
This is great, thank you @drapanjanas

**Pull request closed without merging**
