### PR TITLE
Adds support for UWP and WPF apps (using react-native-windows)

### PR DESCRIPTION
**Pull request by amorokh**
This (big) change adds support for creating projects for UWP and WPF using `react-native-windows`.

I reorganized the .re-natal file to be able to read selected platforms from the file and while doing that I grouped the platform-specific configuration (dev-host and modules).

The UWP and WPF platforms are opt-in so the default behavior of re-natal hasn't changed. It is possible to include UWP and WPF Projects in init but it is also possible to add either platforms later on (using `re-natal windows` or `re-natal wpf`).

### CODE REVIEW

**Comment by drapanjanas** [comment]
Hey! Thanks a lot for this contribution! I will try to test the changes during the weekend (fix if I find something) and merge. It is important not to break things for current users when they upgrade the tool. Thanks for thinking about this!

**Comment by amorokh** [comment]
I totally agree with you regarding upgrade, it must not break things and I did think about that but I am new to Coffeescript and I am not sure about all comparisons so the code definitely needs review.

One thing that bothers me is the `project.clj` file, in order to be able to add `wpf` or `uwp` later on I had to add a marker in the file for build configurations and that will of course not work for upgrade so if you have any better idea on how to handle that, that would be great.

Otherwise, it feels great to contribute!

**Comment by drapanjanas** [comment]
Finally got some time to review and test the changes to find regressions and all seems to work well!!!
About the updates in `project.clj`. I have one idea which I want to try out before releasing. Maybe we could use edn parser like https://github.com/shaunxcode/jsedn to do updates in project.clj. Let me know in case you already tried smth like that.
Anyways, if it doesn't work out this is not a big issue IMO, so I am fine to merge the changes anyway. I will add smth to README and release re-natal 0.4.0

**Comment by amorokh** [comment]
Good to hear that I didn't break something! :)

I was actually thinking of using something like that for editing an existing clj file but didn't know about `jsedn`. If you want I can try it out and also update README with instructions regarding development using VS (it's not working flawlessly, especially not when using VS 2017) before merging and releasing.

**Comment by amorokh** [comment]
Ok, so I tried `jsedn` and since it is `edn` and not `clj` it doesn't support metadata using the `^`character which is present in the `project.clj` template (from what I understand metadata is not part of the `edn`specification).

**Comment by drapanjanas** [comment]
Yeah, also it does not support pretty-printing of edn. Well, it is not better idea after all. 
Regarding README, I do not think full instructions of development using VS are needed. I will add a short chapter about usage of new commands.

**Pull request merged**
