### PR TITLE
fix jvm-opts for java9

### PR DESCRIPTION
**Pull request by stask**
`--add-modules` and `java.xml.bind` should be passed as separate
values in `:jvm-opts`

### CODE REVIEW

**Comment by drapanjanas** [comment]
Thanks for the effort, but this does not work with JDK8 and (most probably) JDK7.

**Comment by drapanjanas** [comment]
Maybe this would work with JDK9? This works with 8
```
:jvm-opts ["-XX:+IgnoreUnrecognizedVMOptions" "--add-modules=java.xml.bind"]
```

**Comment by stask** [comment]
yep, tested on 8 and 9 now

**Comment by drapanjanas** [comment]
Great! Thanks! 👍

**Pull request merged**
