### PR TITLE
Added support for Windows

### PR DESCRIPTION
**Pull request by marxama**
Hey there!

Made some small changes to make things work when running on Windows. Tested on Mac too and doesn't seem to break anything there!

### CODE REVIEW

**Comment by marxama** [comment]
Hmm, I should fix the no-leiningen-handling though, d'oh!

**Comment by drapanjanas** [comment]
Hey! Thanks a lot! 
I will start testing it on my Mac and maybe linux and merge.

**Comment by marxama** [comment]
No probs, I'm very excited about this project so happy to help out!
There was one breaking change though, if Leiningen is not installed the correct error message is no longer printed, I'll try to find a solution to that!

**Comment by marxama** [comment]
Aright, I think that should do it! Not the cleanest solution, but the best I could think of ATM, and works on both Windows (10) and Mac.

Didn't bother to remove the use of 'type' in ensureXcode, but it could be a good idea to show a warning message or something when trying to use the OSX specific commands from other OSs.

Anyway, this is the first time I've touched CoffeeScript, hopefully it's idiomatic enough  :)

**Comment by drapanjanas** [comment]
Its fine, I am also not too much in CoffeeScript, but I like it now :) 
What do you think if this could work (can not try `where` command on windows):
```
ensureExecutableAvailable = (executable) ->
  if os.platform() == 'win32'
    exec "where #{executable}" # expecting that this will throw an error if not exist
  else
    exec "type #{executable}"
```
Then all existing catch blocks would be the same

**Comment by drapanjanas** [comment]
Have quickly tried `where` command on a windows 7 machine at work:
```
C:\Users\t480202>where mvn
C:\Program Files\maven\apache-maven-3.0.4\bin\mvn
C:\Program Files\maven\apache-maven-3.0.4\bin\mvn.bat

C:\Users\t480202>echo Exit Code is %errorlevel%
Exit Code is 0

C:\Users\t480202>where lein
INFO: Could not find files for the given pattern(s).

C:\Users\t480202>echo Exit Code is %errorlevel%
Exit Code is 1
```
So `exec "where #{executable}"` should throw an exception, so we might rethrow it with message same as in case of `"type #{executable}"` and this would make other catch blocks work the same on windows as in Mac and Linux

**Comment by marxama** [comment]
Hey there! Yep, that seems to work, I've made the changes and everything seems to work, thanks!

**Comment by drapanjanas** [comment]
Great, thank you!

**Comment by meiraleal** [comment]
I thought this issue was about Windows UWP support, to be able to use react-native-windows. 
Are Windows integration in the roadmap?

**Pull request merged**
